#!/usr/bin/env bun
// AUTO-GENERATED by `ftask hooks` — do not hand-edit. PreToolUse guard.
// Denies raw git mutations that bypass ftask; fail-open on any error.
const DANGER = [
  /\bgit\b[^&|;]*\bpush\b/,
  /\bgit\b[^&|;]*\bmerge\b/,
  /\bgit\b[^&|;]*\brebase\b/,
  /\bgit\b[^&|;]*\breset\s+--hard\b/,
  /\bgit\b[^&|;]*--force\b/,
  /\bgit\b[^&|;]*\bcheckout\s+--\s/,
];
try {
  const raw = await Bun.stdin.text();
  const ev = JSON.parse(raw) as { tool_name?: string; tool_input?: { command?: string } };
  const cmd = ev.tool_input?.command ?? "";
  if (ev.tool_name !== "Bash" || cmd.length === 0) process.exit(0);
  // Allow anything routed through ftask itself.
  if (/ftask(\.ts)?\b/.test(cmd)) process.exit(0);
  for (const seg of cmd.split(/&&|\|\||;/)) {
    if (DANGER.some((re) => re.test(seg))) {
      console.log(JSON.stringify({ hookSpecificOutput: {
        hookEventName: "PreToolUse", permissionDecision: "deny",
        permissionDecisionReason: "sunke's agent-OS: never run git directly. Use `bun ~/.claude/PAI/TOOLS/ftask.ts` (new/ship/drop/state). Raw git push/merge/rebase/reset --hard/force is blocked.",
      } }));
      process.exit(0);
    }
  }
  process.exit(0);
} catch {
  process.exit(0); // fail-open: a guard bug must never block work
}
